script: gradle build
language: android
android:
  components:
  - build-tools-26.0.2
  - android-26
  - tools
  - platform-tools
  - tools
  licenses:
  - android-sdk-license-.+
deploy:
  provider: releases
  api_key:
    secure: "$GH_TOKEN"
  file_glob: true
  file: FDAndroidClient/build/outputs/apk/*
  skip_cleanup: true
  on:
    repo: freedomotic/fd-android-client
    tags: true

